name: Deploy Review

on:
  pull_request:
    branches: [development]

jobs:
  create_env:
    uses: alexey-ban/ai-dial-ci/.github/workflows/gh_env.yml@review_env
    secrets: inherit
    with:
      environment_name: pr-${{ github.event.pull_request.number }}
      environment_url: "https://chat-ai-dial-themes-pr-${{ github.event.pull_request.number }}.gke.test.epam-rail.com"

  build_docker:
    uses: alexey-ban/ai-dial-ci/.github/workflows/generic_docker_review.yml@review_env
    secrets: inherit   
    needs:
      - create_env
    with:
      environment_name: pr-${{ github.event.pull_request.number }}
      
  deploy_helm:
    uses: alexey-ban/ai-dial-ci/.github/workflows/k8s_env.yml@review_env
    needs:
      - create_env
      - build_docker
    with:
      cloud_provider: "gcp"
      k8s_namespace: ${{ github.repository_id }}-pr-${{ github.event.pull_request.number }}
      helm_values_file: "./build/helm/review.yaml"
      helm_values: "global.url=ai-dial-themes-pr-${{ github.event.pull_request.number }}.gke.test.epam-rail.com,themes.image.registry=${{ needs.build_docker.outputs.image_registry }},themes.image.repository=${{ needs.build_docker.outputs.image_repository }},themes.image.tag=${{ needs.build_docker.outputs.image_tag }}" # for epam we can delete themes.image.repository
      helm_extra_args: "--set-file core.extraConfig=./build/helm/review_core.json"

  run_e2e:
    uses: alexey-ban/ai-dial-ci/.github/workflows/run_e2e_test.yml@review_env
    needs:
      - deploy_helm
    with:
      url: "https://chat-ai-dial-themes-pr-${{ github.event.pull_request.number }}.gke.test.epam-rail.com"
      environment_name: pr-${{ github.event.pull_request.number }}