name: Destroy Review

on:
  pull_request:
    branches: [development]
    types: [closed]

jobs:
  cancel-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: "Cancel Workflow"
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # v0.12.1
        with:
          ignore_sha: true
          workflow_id: "all"

  delete-k8s-env:
    uses: alexey-ban/ai-dial-ci/.github/workflows/k8s_env.yml@review_env
    needs:
      - cancel-workflows
    with:
      cloud_provider: "gcp"
      helm_operation: "uninstall"
      k8s_namespace: ${{ github.repository_id }}-pr-${{ github.event.pull_request.number }}

  delete-gh-environment:
    runs-on: ubuntu-latest
    needs:
      - cancel-workflows    
    steps:
      - name: Sleep to debug # need delay between cancel workflow and delete environment
        run: |
            sleep 10
      - name: Delete Github environment
        uses: strumwolf/delete-deployment-environment@a4825dd9648c57da8437a4885c3fcad58beac69c # v3.0.0
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          environment: pr-${{ github.event.pull_request.number }}

