name: Delete Environment

on:
  workflow_call:
    inputs:
      environment_name:
        type: string
        description: "The name of the environment to manage"
        required: true
      environment_destroy:
        type: boolean
        description: "Destroy environment"
        default: false

jobs:
  cancel-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: "Cancel Workflow"
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # v0.12.1
        with:
          ignore_sha: true
          workflow_id: "all"

  delete-k8s-env:
    uses: ./.github/workflows/helm_deploy.yml
    needs:
      - cancel-workflows
    with:
      cloud_provider: "gcp"
      helm_operation: "uninstall"
      k8s_namespace: ${{ github.repository_id }}-pr-${{ github.event.pull_request.number }}

  delete-environment:
    runs-on: ubuntu-latest
    needs:
      - cancel-workflows
    steps:
      - name: Sleep to debug # need delay between cancel workflow and delete environment
        run: |
            sleep 5
      - name: Delete Github environment
        if: ${{ inputs.environment_destroy}}
        uses: strumwolf/delete-deployment-environment@a4825dd9648c57da8437a4885c3fcad58beac69c # v3.0.0
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          environment: ${{ inputs.environment_name }}

